# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20171108_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='Order',
        ),
    ]
