# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_verifycode_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
